### ISSUE TITLE
Feature Request - Add custom text to webhook notifications

### ISSUE THREAD

**Issue by edrock200** [willfarrell/docker-autoheal#118]
Respectfully requesting the ability to append the webhook notifications with custom text. Reason being if you have autoheal on multiple hosts with similarly named containers, aside from the container id, its difficult to discern which host the notification is coming from. If we deploy it to add, for example, the hostname appended to the webhook, it will quickly identify the container and host in the webhook notification. Thanks in advance for your consideration.

**Comment by christiantosta** [comment]
If you are running with docker-compose, you can append the node name to the project name:

- Node1:
```
name: my-project-node1
services:
  app:
    deploy:
      replicas: 2
    (...)
```

- Node2:
```
name: my-project-node2
services:
  app:
    deploy:
      replicas: 2
    (...)
```


So your containers will be named:

my-project-node1-app-1
my-project-node1-app-2
my-project-node2-app-1
my-project-node2-app-2
