### ISSUE TITLE
Autoheal is healing ALL containers not just the ones with label

### ISSUE THREAD

**Issue by addrum** [willfarrell/docker-autoheal#124]
Running autoheal with the following compose:
```
version: "3"
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    environment:
      - PGID=65537
      - PUID=1029
      - TZ=Europe/London
    network_mode: bridge
    restart: always
    volumes:
      - /volume1/docker/docker.sock:/var/run/docker.sock
```

Have the following label as described in the readme defined on specific services:
```
    labels:
      - autoheal=true
```

Yet autoheal is also healing containers without the label above (can see so in the logs). Am I doing something wrong?
