### ISSUE TITLE
unfortunately not working on ARM architechture / RaspberryPi's

### ISSUE THREAD

**Issue by RezzZ** [willfarrell/docker-autoheal#19]
Any chance we can get a build that works on a raspberry pi (3?)

**Comment by FranklinYu** [comment]
Shouldn't this have been solved by #14?

**Comment by RezzZ** [comment]
@FranklinYu 
hmm, I keep getting this error and container keeps restarting:
```
standard_init_linux.go:207: exec user process caused "exec format error"
```
any ideas what might be wrong? I use docker-compose:
```
version: '2.1'
services:

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    restart: always
    volumes:
      - /opt/autoheal:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=homeassistant
      - AUTOHEAL_START_PERIOD=120
```
and the container homeassistant is the container name I would like to monitor so I created a label there:
```
    labels:
      - "autoheal=true"
```
