### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by kiwijunglist** [willfarrell/docker-autoheal#27]
Hi

I can understand how to "autoheal" all containers (option b), but I'm unclear how to auto heal a specific container or a specific list of containers (option a or c).

Can you please provide examples.

Would this be correct for docker-compose to monitor the jackett container, but not the radarr container.

```
version: '3.4'
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=jackett
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 9117:9117
    healthcheck:
      test: curl --fail -s http://localhost:9117/UI/Dashboard || exit 1
      interval: 90s
      timeout: 3s
      retries: 3
    labels:
      - autoheal=true
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 8787:8787
```

**Comment by willfarrell** [comment]
Hi @kiwijunglist, sorry the Docs are as good as they could be. I've set some time aside next month to work on this repo, I'll revisit the dos when I do.

For the above case, `AUTOHEAL_CONTAINER_LABEL=jackett` should be `AUTOHEAL_CONTAINER_LABEL=autoheal` or remove as `autoheal` is the default value.

**Comment by kiwijunglist** [comment]
Hi Will. thanks!

**Comment by kiwijunglist** [comment]
is the format for the jackett container correct?
```
services:
  jackett:
    labels:
      - autoheal=true
```

**Comment by willfarrell** [comment]
Yep!

**Comment by willfarrell** [comment]
@kiwijunglist is this better? https://github.com/willfarrell/docker-autoheal/blob/fe0437ef98f0838e65398020a6192922dc8b402b/docs/README.md

**Comment by kiwijunglist** [comment]
yes i think i understand that, and most other people should be able to as well.

you could add a file called docker-compose-example.yaml

```
# Example of how to use docker compose with autoheal

# Example 1.  Setup autoheal to watch all containers using autoheal_container_label=true

version: '3.4'
services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Example 2. Setup autoheal to watch a single container (Radarr) using autoheal=true

version: '3.4'
services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:7878 || exit 1
      interval: 90s
      timeout: 3s
      retries: 3
    labels:
      - autoheal=true

# Example 3.  Setup autoheal to only restart containers with the label customlabel=true

version: '3.4'
services:
  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=watchme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  alpha:
    image: linuxserver/alpha
    container_name: alpha
    restart: unless-stopped
    healthcheck:
      # code here
    labels:
      - customlabel=true
  beta:
    image: linuxserver/beta
    container_name: beta
    restart: unless-stopped
    healthcheck:
      # code here
    labels:
      - customlabel=true
  stable:
    image: linuxserver/stable
    container_name: stable
    restart: unless-stopped
    healthcheck:
      # code here
```
