### ISSUE TITLE
 /docker-entrypoint: exec: line 101: autoheal: not found

### ISSUE THREAD

**Issue by thewinger** [willfarrell/docker-autoheal#48]
Hi

I'm using docker-autoheal in a docker-compose file but with a socket-proxy service (fluencelabs/docker-socket-proxy)

```
autoheal:
  image: willfarrell/autoheal
  container_name: autoheal
  restart: unless-stopped
  networks:
    - t2_proxy
    - socket_proxy
  depends_on:
    - socket-proxy
  environment:
    - AUTOHEAL_CONTAINER_LABEL=all
``` 

Because of this I don't use the volume /var/run/docker.sock but a network socket_proxy

When I run docket-autoheal I see in the logs file only this line repeating

/docker-entrypoint: exec: line 101: autoheal: not found.

Does this affect at how the container is working?

**Comment by zhorvath83** [comment]
I tried to pair willfarrell/autoheal with tprasadtp/docker-socket-proxy, but found the same issue.


```
autoheal: 
    image: willfarrell/autoheal:latest
    container_name: autoheal
    depends_on:
      - socketproxy
    networks:
      - socketproxynet
    environment:
      DOCKER_SOCK: tcp://socketproxy:2375
      AUTOHEAL_INTERVAL: 5
      AUTOHEAL_START_PERIOD: 0
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 30
    labels:
      diun.enable: "true"
    restart: unless-stopped
```

> 2020-12-07T07:36:27.214593318Z /docker-entrypoint: exec: line 101: autoheal: not found

Other containers (Watchtower, Diun, Portainer) works well with this companion.

@thewinger Have you added the DOCKER_SOCK environment variable instead of mounting the docker sock directly to your autoheal container?
