### ISSUE TITLE
Referencing environment variables from .env file make system crash

### ISSUE THREAD

**Issue by kikearciniegas** [willfarrell/docker-autoheal#59]
This is my docker-compose file:
```
services:
  autoheal:
  # https://github.com/willfarrell/docker-autoheal
  # monitor and restart unhealthy docker containers
  # - no health check available (if it fails, it just restarts by default)  
    image: willfarrell/autoheal
    container_name: autoheal
    environment: # referecing environment tags from .env file give errors and make the system stop
      - AUTOHEAL_CONTAINER_LABEL=${AH_CONTAINER_LABEL}
      - AUTOHEAL_INTERVAL=${AH_INTERVAL}
      - AUTOHEAL_START_PERIOD=${AH_START_PERIOD}
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AH_DEFAULT_STOP_TIMEOUT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels: 
      - autoheal=true
    restart: always
```
and these are the environment variables within the .env file:
```
AH_RESTART=true
AH_CONTAINER_LABEL=all
AH_INTERVAL=5
AH_START_PERIOD=15
AH_DEFAULT_STOP_TIMEOUT=30
```
When I run the image as it is, i get these errors:
```
sleep: invalid number '5   # check every 5 seconds'
Container /autoheal (f2ecb832259a) found to be unhealthy - Restarting container now with 10s timeout
```
and
```
jq: 1 compile error
sh: 15   # wait 15 seconds before first health check: bad number
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
foreach .[] as $CONTAINER([];[]; $CONTAINER | .Id, .Names[0], .Labels["autoheal.stop.timeout"] // 30   # Docker waits max 10 seconds (the Docker default) for a container to stop before killing during restarts) 
Container stopped
```
But when I run the env vars plainly like this:
```
services:
  autoheal:
  # https://github.com/willfarrell/docker-autoheal
  # monitor and restart unhealthy docker containers
  # - no health check available (if it fails, it just restarts by default)  
    image: willfarrell/autoheal
    container_name: autoheal
    environment: # referecing environment tags from .env file give errors and make the system stop
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=15
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels: 
      - autoheal=true
    restart: always
```
Then the container runs normally... This only happens with autoheal, as I have all other containers pulling env vars from the .env file without issues.

Also noticed that the issue just happens with env vars, as labels, volumes and any other block do take the referenced tag just fine.

Expected behavior:
To take the value from the referenced variable and run without errors or stopping.

Thanks for the hard work!
