### ISSUE TITLE
Container exits instead of restarting

### ISSUE THREAD

**Issue by jeritiana** [willfarrell/docker-autoheal#67]
Hi there,

I could get some help please because my container exits instead of the restarting behavior I would expect.

The use case is:
* A service named `gateway` has access to some distant host `10.0.0.42` by setting up an authenticated VPN connection
* A service named `proxy` makes use of `gateway`'s network stack to get access to this distant host

`gateway` would restart from time to time because the VPN connection can break. If `gateway` restarts, I also have to restart `proxy`. If the VPN server does not respond, `gateway` would keep restarting until the connection is established again.

Here is a representative configuration one can try easily:
```
version: '3.5'
services:

  proxy:
    image: marcnuri/port-forward
    restart: unless-stopped
    environment:
      - REMOTE_HOST=10.0.0.42
      - REMOTE_PORT=8080
    labels:
      autoheal: "true"
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "10.0.0.42"]
      interval: 20s
      timeout: 15s
      retries: 1
      start_period: 10s
    depends_on:
      - gateway
    network_mode: service:gateway

  gateway:
    image: alpine
    restart: unless-stopped
    command: sleep 10
    labels:
      autoheal: "true"
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "10.0.0.42"]
      interval: 20s
      timeout: 15s
      retries: 1
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal:1.1.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

In this sample configuration, `gateway` always restarts, which is the required behavior simulation. I would expect for `proxy` to also restart, but instead it exits. Am I missing something?

Thanks guys

**Comment by hasnat** [comment]
I think autoheal does not care about stopped/exit containers, only unhealthy ones.
your restarts might be coming from docker restart policy

**Comment by jeritiana** [comment]
Hum... I think autoheal here is responsible for the restarts, and that is expected.

From the healthcheck, `10.0.0.42` does not resolve and `ping 10.0.0.42` fails, leading to unhealthy containers to be restarted by autoheal. That is expected too.

What is unexpected and the issue is that, instead of restarting, the `proxy` container exits. As you said, autoheal does not care about it anymore and the container remains exited forever instead of being restarted.

The thing I dont understand is why it exits instead of being restarted by autoheal.

**Comment by hasnat** [comment]
think your container is designed to die on errors, more would be on logs. What you might be after here is tweak on restart policy to restarts forever. https://docs.docker.com/config/containers/start-containers-automatically/#restart-policy-details

For autoheal
https://comb.io/FIw7B2.gif

**Comment by jeritiana** [comment]
I think I found why it is behaving like this. It can be a race condition between the container restarts.

To sum up:
* container A keeps restarting. It is expected because container A is unhealthy. Autoheal restarts container A.
* container B depends on container A. As it is also considered to be unhealthy, autoheal restarts container B.
* if container B is restarted in between container A restarts (i.e. container A is not ready), Docker considers that the dependency is not satisfied and kills container B.
* as container B has now exited, autoheal would never resuscitate it.

I am going to close the issue as it is not directly linked to autoheal. Well, we could handle container restarts and dependencies in autoheal but that would be another story.

Thanks guys.

**Comment by arcoast** [comment]
@jeritiana 

I've just hit the same problem.  I'm wondering if a reasonable workaround might be either:

1.  Remove this from `proxy`
 ```yaml
depends_on:
      - gateway
 ```
and just rely on autoheal restarting the container until the dependency on `gateway` is fulfilled

Or

2.   Set the restart policy for `proxy` to:
 ```yaml
restart: always
```
so it just keeps restarting even if it fails.

Wondering if you've got any other thoughts?

**Comment by bluefangs** [comment]
> * if container B is restarted in between container A restarts (i.e. container A is not ready), Docker considers that the dependency is not satisfied and kills container B.

I think `depends_on` with `service_healthy` might help here. Unless container A is in a healthy condition, container B will not come up after it was restarted previously. Worth a try perhaps. 

For containerB:

```
containerB:
    ...
    depends_on:
        containerA: 
              condition: service_healthy
```
