### ISSUE TITLE
autoheal not working :(

### ISSUE THREAD

**Issue by stepanov1975** [willfarrell/docker-autoheal#92]
I am using docker-compose:
```
version: '3.3'
services:
  autoheal:
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/localtime:/etc/localtime:ro'
    image: willfarrell/autoheal
```
Creating container:
```
[root@docker-fedora-nuc autoheal]# docker-compose up
Recreating autoheal ... done
Attaching to autoheal
```
That is all. No log no nothing. What am I missing?
