### ISSUE TITLE
autoheal container constantly restarts. "autoheal exited with code 7"

### ISSUE THREAD

**Issue by dziban303** [willfarrell/docker-autoheal#93]
When trying to add autoheal to my container stack, it seems to fail and restart over and over. "autoheal exited with code 7" is emitted to the log each time. Google hasn't been particularly helpful; in particular, there are no results at all for this error message, which doesn't bode well for me. 

This is how I have autoheal set up in my compose file:

```yml
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

I've tried it on several stacks with the same result. The system is a Pi4 4GB on Bullseye. Docker version 20.10.19, build d85ef84. 

I had it running without issue on an identical stack on this Pi once before, but after reimaging and starting over the issue began. It has never run successfully in the system's current incarnation.

Any ideas?
